name: Create M3U Playlists

on:
  schedule:
    - cron: "5 4 * * *" # Run once a day
  workflow_dispatch: # Allow manual triggering

jobs:
  update-list:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5

      - name: Configure Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Run the scraper
        run: uvx --from "git+https://github.com/kism/acerestreamer" acerestreamer-scrape --app-config config.json
        env:
          UV_GIT_LFS: 1

      - name: Configure git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Commit and Push Changes
        run: |
          git add .
          if [ "$(git diff --cached --numstat | wc -l)" -gt 1 ]; then
            git commit -m "Update m3u"
            git push
          else
            echo "No changes to commit, ignoring README.md."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
